import { Button } from "@/components/ui/button";
import { FileText, Download, Printer, Scale } from "lucide-react";

const DocumentGenerator = () => (
  <div className="space-y-6">
    <div>
      <h1 className="text-2xl font-display font-bold text-foreground">Document Generator</h1>
      <p className="text-muted-foreground text-sm mt-1">Generate court-ready legal documents from case data</p>
    </div>

    {/* Document Preview */}
    <div className="bg-card rounded-xl border border-border overflow-hidden">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-6 py-3 border-b border-border bg-muted/30">
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <FileText className="w-4 h-4" /> Legal Document — Case DV-2024-0891
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm"><Printer className="w-4 h-4 mr-1" /> Print</Button>
          <Button variant="outline" size="sm"><Download className="w-4 h-4 mr-1" /> Download</Button>
          <Button variant="hero" size="sm">Generate PDF</Button>
        </div>
      </div>

      {/* Document Content */}
      <div className="p-8 md:p-12 max-w-3xl mx-auto">
        {/* Header */}
        <div className="text-center border-b-2 border-foreground pb-6 mb-8">
          <div className="w-16 h-16 mx-auto mb-3 rounded-full bg-muted flex items-center justify-center">
            <Scale className="w-8 h-8 text-foreground" />
          </div>
          <h2 className="text-xl font-display font-bold text-foreground uppercase tracking-wider">In the Court of Metropolitan Magistrate</h2>
          <p className="text-sm text-muted-foreground mt-1">Mumbai, Maharashtra</p>
        </div>

        <div className="text-center mb-8">
          <p className="text-sm text-muted-foreground">Case No: DV-2024-0891</p>
          <h3 className="text-lg font-semibold text-foreground mt-1">State vs. Rajesh Sharma</h3>
          <p className="text-sm text-muted-foreground">Under Section 498A, Indian Penal Code</p>
        </div>

        {/* Sections */}
        {[
          {
            title: "I. Statement of Facts",
            content: "The complainant, Priya Sharma, aged 28 years, resident of Andheri West, Mumbai, has filed the present complaint against her husband, Rajesh Sharma. The complainant states that she has been subjected to domestic violence, including physical assault and mental cruelty, over a period of approximately three (3) years since the date of marriage."
          },
          {
            title: "II. Timeline of Events",
            content: "• March 2022 — First incident of physical assault reported to family members\n• August 2022 — Complainant sought medical treatment for injuries\n• January 2023 — Neighbor (Witness #1) observed threatening behavior\n• December 2024 — Formal complaint filed with Mumbai Police"
          },
          {
            title: "III. Evidence Summary",
            content: "1. Voice testimony recordings (3 sessions, AES-256 encrypted)\n2. Medical records from Kokilaben Hospital\n3. Witness statement from Mrs. Sunita Iyer (neighbor)\n4. Phone call records and text message logs\n5. Cognitive map analysis showing pattern of escalation"
          },
          {
            title: "IV. Prayer",
            content: "In light of the above facts and evidence, the complainant humbly prays before this Hon'ble Court to take cognizance of the matter and provide appropriate relief and protection under the provisions of the Protection of Women from Domestic Violence Act, 2005."
          },
        ].map((section) => (
          <div key={section.title} className="mb-8">
            <h4 className="text-sm font-bold text-foreground uppercase tracking-wide mb-3">{section.title}</h4>
            <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">{section.content}</p>
          </div>
        ))}

        <div className="border-t border-border pt-6 mt-10 flex justify-between text-xs text-muted-foreground">
          <span>Generated by Sahayak AI • {new Date().toLocaleDateString()}</span>
          <span>Page 1 of 1</span>
        </div>
      </div>
    </div>
  </div>
);

export default DocumentGenerator;
