"""
config.py — Single source of truth for all environment variables and app-level constants.
"""
import os
from dotenv import load_dotenv

load_dotenv()

# ── MongoDB ────────────────────────────────────────────────────────────────────
MONGO_URI: str = os.getenv("MONGO_URI")
if not MONGO_URI:
    raise ValueError("MONGO_URI is not set in environment variables")

MONGO_DB_NAME: str = os.getenv("MONGO_DB_NAME", "sahayak_db")

COLLECTION_FRAGMENTS: str     = os.getenv("COLLECTION_FRAGMENTS",     "fragments")
COLLECTION_TESTIMONIES: str   = os.getenv("COLLECTION_TESTIMONIES",   "testimonies")
COLLECTION_EVIDENCE: str      = os.getenv("COLLECTION_EVIDENCE",      "evidence")
COLLECTION_CONVERSATIONS: str = os.getenv("COLLECTION_CONVERSATIONS", "conversations")
COLLECTION_DOCUMENTS: str     = os.getenv("COLLECTION_DOCUMENTS",     "documents")
COLLECTION_CASES: str         = os.getenv("COLLECTION_CASES",         "cases")
COLLECTION_USERS: str         = os.getenv("COLLECTION_USERS",         "users")
COLLECTION_MEDIA_UPLOADS: str = os.getenv("COLLECTION_MEDIA_UPLOADS", "media_uploads")
COLLECTION_SHARED_LINKS: str  = os.getenv("COLLECTION_SHARED_LINKS",  "shared_links")
COLLECTION_COMMUNITY_STORIES: str = os.getenv("COLLECTION_COMMUNITY_STORIES", "community_stories")

# ── Cloudinary ─────────────────────────────────────────────────────────────────
CLOUDINARY_CLOUD_NAME: str = os.getenv("CLOUDINARY_CLOUD_NAME", "")
CLOUDINARY_API_KEY: str    = os.getenv("CLOUDINARY_API_KEY", "")
CLOUDINARY_API_SECRET: str = os.getenv("CLOUDINARY_API_SECRET", "")

# ── AES-256 Encryption ─────────────────────────────────────────────────────────
AES_ENCRYPTION_KEY: str = os.getenv("AES_ENCRYPTION_KEY", "")
SHARE_LINK_EXPIRY_HOURS: int = int(os.getenv("SHARE_LINK_EXPIRY_HOURS", "48"))

# ── JWT Authentication ─────────────────────────────────────────────────────────
JWT_SECRET_KEY: str = os.getenv("JWT_SECRET_KEY")
if not JWT_SECRET_KEY:
    raise ValueError("JWT_SECRET_KEY is not set")

JWT_ALGORITHM: str = os.getenv("JWT_ALGORITHM", "HS256")
JWT_EXPIRY_MINUTES: int = int(os.getenv("JWT_EXPIRY_MINUTES", "1440"))

# ── Gemini ─────────────────────────────────────────────────────────────────────
GEMINI_API_KEY: str = os.getenv("GEMINI_API_KEY", "")
GEMINI_API_KEY_DOCS: str = os.getenv("GEMINI_API_KEY_DOCS", GEMINI_API_KEY)
GEMINI_API_KEY_MAP: str = os.getenv("GEMINI_API_KEY_MAP", GEMINI_API_KEY)
GEMINI_API_KEY_INSIGHTS: str = os.getenv("GEMINI_API_KEY_INSIGHTS", GEMINI_API_KEY)
GEMINI_API_KEY_CHAT: str = os.getenv("GEMINI_API_KEY_CHAT", GEMINI_API_KEY)

GEMINI_MODEL: str = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
GEMINI_TIMEOUT_DEFAULT: float = float(os.getenv("GEMINI_TIMEOUT_DEFAULT", "40"))
GEMINI_TIMEOUT_DRAFT: float = float(os.getenv("GEMINI_TIMEOUT_DRAFT", "60"))

# ── Claw Law external search ───────────────────────────────────────────────────
CLAWLAW_JUDGMENT_URL: str = os.getenv(
    "CLAWLAW_JUDGMENT_URL", "https://clawlaw.in/judgment"
)

# ── CORS ───────────────────────────────────────────────────────────────────────
_raw_origins: str = os.getenv("CORS_ORIGINS", "")
CORS_ORIGINS: list[str] = [o.strip() for o in _raw_origins.split(",") if o.strip()]

if not CORS_ORIGINS:
    raise ValueError("CORS_ORIGINS must be set in environment variables")

# ── App metadata ───────────────────────────────────────────────────────────────
APP_TITLE: str       = os.getenv("APP_TITLE",       "Sahayak Cognitive Map API")
APP_VERSION: str     = os.getenv("APP_VERSION",     "3.0")
APP_DESCRIPTION: str = os.getenv("APP_DESCRIPTION", "Claw Legal Integration — Multi-Case")

# ── Defaults ───────────────────────────────────────────────────────────────────
DEFAULT_CASE_ID: str            = os.getenv("DEFAULT_CASE_ID", "default")
TIMESTAMP_FORMAT: str           = os.getenv("TIMESTAMP_FORMAT", "%Y-%m-%d %H:%M")
DEFAULT_FRAGMENT_TIMESTAMP: str = os.getenv("DEFAULT_FRAGMENT_TIMESTAMP", "Just now")

# ── Legal branding ─────────────────────────────────────────────────────────────
POWERED_BY_BNS: str   = os.getenv("POWERED_BY_BNS",   "Claw LegalGPT × Sahayak")
POWERED_BY_GAP: str   = os.getenv("POWERED_BY_GAP",   "Claw ATG + AI × Sahayak")
POWERED_BY_DRAFT: str = os.getenv("POWERED_BY_DRAFT", "Claw Adira AI × Sahayak")
POWERED_BY_FULL: str  = os.getenv("POWERED_BY_FULL",  "Claw Adira AI + LegalGPT + ATG × Sahayak")
POWERED_BY_CASES: str = os.getenv("POWERED_BY_CASES", "Claw Judgment Search × Sahayak")

LEGAL_DRAFT_DISCLAIMER: str = os.getenv(
    "LEGAL_DRAFT_DISCLAIMER",
    (
        "This draft was generated by Claw Adira AI integration within Sahayak. "
        "It must be reviewed and certified by a qualified advocate before submission "
        "to any court or authority."
    ),
)

# ── Contradiction chat ─────────────────────────────────────────────────────────
FALLBACK_CHAT_REPLY: str = os.getenv(
    "FALLBACK_CHAT_REPLY", "Noted. Please continue with your testimony."
)